# -*- coding: utf-8 -*-
"""Lista_Exercicios6_Aldenis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ucl_5JORFI4PehPnSGlLbw717O3h8xGB

###IFPE Jaboatão
###Tecnologia em Análise e Desenvolvimento de Sistemas
###Disciplina: Lógica de Programação
###Professora: Havana Alves
###Aluno: Aldenis Everton Alves Guilherme de França

##Lista de Exercícios 6

1) Escreva uma função que receba o tamanho de dois catetos de um triângulo
como seus parâmetros e calcule a hipotenusa. A função deve apenas imprimir o
resultado.
"""

def hipotenusa(c1,c2):
  h = ((c1**2) + c2**2)**(1/2)
  return round(h,2)

hipotenusa(10,8)

"""2) Uma empresa de logística realiza entrega expressa a RS 59.67 pelo primeiro
item, e a RS 16,07 para cada item a mais. Escreva uma função que receba a
quantidade de itens como parâmetro. A função deve retornar o valor que o
cliente irá pagar. Utilize essa função em um programa que peça a quantidade de
itens ao cliente e que depois exiba o valor a ser pago.
"""

def custo_logistico(n):
  if n <= 0:
    print('\nVocê digitou um número inválido!')
  else:
    custo = 59.67 + (n-1)*16.07
    return custo

itens = int(input(f'Digite a quantidade de itens: '))
c = custo_logistico(itens)
print(f'\nO Custo Logístico é de R$ {c:.2f}')

"""3) Se você possui três retas, que podem ser ou não de comprimentos diferentes,
estas podem formar um triângulo, ou não. Dados os lados a, b e c, é necessário
que todas as condições a seguir sejam atendidas para que um triângulo possa
ser formado :

| b - c | < a < b + c

| a - c | < b < a + c

| a - b | < c < a + b

Escreva uma função que receba uma lista com os três comprimentos e retorne
um booleano que indique se formam um triângulo válido ou não. Um programa
deve chamar esta função. Neste programa os três lados devem ser solicitados
ao usuário, e deve ser exibido a ele se os valores inseridos possibilitam a
existência de um triângulo.
"""

def existe_triangulo(r1, r2, r3):
  if abs(r2 - r3) < r1 < (r2 + r3) and abs(r1 - r3) < r2 < (r1 + r3) and abs(r1 - r2) < r3 < (r1 + r2):
    return True

r = []
for i in range(1,4):
  retas = float(input(f'Digite o valor da {i}ª reta: ').replace(',','.'))
  r.append(retas)

if existe_triangulo(r[0],r[1],r[2]) == True:
  print('\nEssas três retas formam um Triângulo.')
else:
  print('\nNão é possível formar um Triângulo com essas retas.')

"""4) Escreva uma função que receba o total gasto pelo cliente e a opção de
pagamento, que pode ser:

1) Opção: à vista com 10% de desconto

2) Opção: em duas vezes (preço da etiqueta)

3) Opção: de 3 até 10 vezes com 3% de juros ao mês (somente para compras
acima de R$ 100,00).

Chame esta função em um programa que receba estes dados do usuário.
"""

def gastosCliente(total_gasto):
  print('')
  print('-' * 60)
  print('{:^60}'.format('OPÇÕES DE PAGAMENTO'))
  print('-' * 60)
  if 0 < total_gasto <= 100:
    opcao_pgto = int(input(f'\nEscolha a opção de pagamento:\n1 - À vista com 10% de desconto\n2 - Em 2x sem juros\nDigite 1 ou 2: '))
    
    if opcao_pgto == 1:
      valor_pagar = total_gasto * 0.9
      return print(f'\nVocê irá pagar R$ {valor_pagar:.2f}')
    elif opcao_pgto == 2:
      valor_pagar = total_gasto / 2
      return print(f'\nVocê irá pagar duas parcelas de R$ {valor_pagar:.2f} cada.')
    else:
      return print(f'\nVocê digitou um número inválido.')

  elif total_gasto > 100:
    opcao_pgto = int(input(f'\nEscolha a opção de pagamento:\n1 - À vista com 10% de desconto.\n2 - Em 2x sem juros.\n3 - De 3 a 10x com juros de 3% a.m.\nDigite 1, 2 ou 3: '))
    if opcao_pgto == 1:
      valor_pagar = total_gasto * 0.9
      return print(f'\nVocê irá pagar R$ {valor_pagar:.2f}')
    elif opcao_pgto == 2:
      valor_pagar = total_gasto / 2
      return print(f'\nVocê irá pagar duas parcelas de R$ {valor_pagar:.2f} cada.')
    elif opcao_pgto == 3:
      parcelas = int(input(f'\nVocê deseja dividir em quantas vezes (de 3 a 10x): '))
      if parcelas < 3 or parcelas > 10:
        return print(f'\nVocê digitou um número inválido.')
      else:
        valor_pagar = (total_gasto * 1.03) / parcelas
        return print(f'\nVocê irá pagar {parcelas} parcelas de R$ {valor_pagar:.2f} cada.')
    else:
      return print('\nVocê digitou um número inválido.')
  
  else:
    return print('\nVocê digitou um número inválido.')

compras = float(input(f'Digite o valor gasto pelo cliente: R$ ').replace(',','.'))
gastosCliente(compras)

"""5) Sabendo que a fórmula do cálculo da distância percorrida de um veículo em um
movimento uniformemente variado é dado por x = v 0 *t + a*t² e que a fórmula da
velocidade final é dada por v f = v 0 + a*t, crie uma função que receba a velocidade final, o tempo e a aceleração do veículo e retorne a distância
percorrida.
"""

def MUV(velFinal,tempo,acel):
  unidTempo = input('Informe a unidade de tempo utilizada [h, m ou s]: ').strip()[0]
  velFinal = (velFinal / 3.6)
  if unidTempo in 'sS':
    tempo = tempo
  elif unidTempo in 'mM':
    tempo = tempo * 60
  elif unidTempo in 'hH':
    tempo = tempo * 3600
  else:
    print('Unidade Inválida!')

  v0 = velFinal - (acel * tempo)
  s0 = (v0 * tempo) + ((acel * (tempo ** 2)) / 2)
  return print(f'\nA Distância Percorrida em km foi de: {(s0 / 1000):.2f} km.')

print('')
print('-' * 50)
print('{:^50}'.format('DISTÂNCIA PERCORRIDA POR UM VEÍCULO'))
print('-' * 50)

velFinal = float(input('Informe a Velocidade Final, em km/h: '))
tempo = float(input('Informe o Tempo percorrido: '))
acel = float(input('Informe a Aceleração, em m/s²: '))

MUV(velFinal,tempo,acel)

"""6) Escreva uma função que gere uma senha aleatória. A senha deve ter um
tamanho aleatório que pode ser de 7 a 10 caracteres. Cada caracter deve ser
randomicamente escolhido das posições 33 a 126 da tabela ASCII. A função
não deve receber parâmetros, apenas retornar a senha pronta quando for
chamada. Um programa deve chamar a função e imprimir a senha gerada.
"""

def senhaAleatoria():
  from random import randint
  qtdCarac = randint(7,10)
  
  for i in range(0, qtdCarac):
    caracter = randint(33,126)
    dec2asc = chr(caracter)
    senha = print(''.join(dec2asc), end='')
  return senha

print('')
print('-' * 40)
print('{:^40}'.format('PRIMEIRO ACESSO - CADASTRO'))
print('-' * 40)

login = input(str('\nInforme um login: '))
opcaoSenha = int(input('\nPara sua senha, escolha:\n1 - Para gerar uma senha aleatória.\n2 - Para criar sua própria senha.\nDigite 1 ou 2: '))
if opcaoSenha == 1:
  print(f'\nSeu Login: {login}\nSua Senha: ', end='')
  senhaAleatoria()
elif opcaoSenha == 2:
  senha = input('Digite sua senha de 7 a 10 caracteres: ')
  print(f'\nSeu Login: {login}\nSua Senha: {senha}')
else:
  print('\nVocê digitou um número inválido.')

"""7) A função que indica a concentração de álcool no sangue de uma pessoa em
relação ao tempo é dada por N(t) = -0.008(t2 - 35t + 34). Considere
que uma pessoa começou a beber no tempo t0, em que N(t0) = 0, partindo de um
estado de sobriedade, e que parou de beber no tempo t1 e que em t2 voltou ao
estado de sobriedade. A função tem gráfico exibido na imagem a seguir:

Sabendo que temos as seguintes fórmulas referentes a uma função de 2º grau:
Vértices da função: xv = -b/2a yv = -Δ/4a
Delta: Δ = b2 - 4ac
Báskhara: 𝑥 = − 𝑏 ± Δ/2𝑎

Crie funções em Python que utilizem as fórmulas corretas para saber qual o
máximo de concentração de álcool que a pessoa irá alcançar e em quanto tempo isto
irá acontecer, e com quanto tempo após o início da cachaçada o indivíduo ficará sóbrio,
baseando-se nas informações fornecidas? Estas funções devem ser utilizadas em um programa que irá exibir as informações calculadas.
"""

def concentMaxAlc():
  coeficiente = -0.008
  a = 1
  b = -35
  c = 34
  delta = (b**2) - 4*a*c
  concMax = round(- delta / (4*a),2)*coeficiente
  return concMax

def timeMaxConc():
  a = 1
  b = -35
  tempo = -b / (2*a)
  return tempo

def tempoSobrio():
  coeficiente = -0.008
  a = 1
  b = -35
  c = 34
  delta = (b**2) - 4*a*c
  raiz1 = (-b + (delta)**(1/2)) / 2*a
  raiz2 = (-b - (delta)**(1/2)) / 2*a
  if raiz1 < raiz2:
    return (raiz2-raiz1)
  else:
    return (raiz1-raiz2)

print('')
print('-' * 80)
print('{:^80}'.format('CONCENTRAÇÃO DE ÁLCOOL NO CORPO HUMANO'))
print('-' * 80)
print('')

c = concentMaxAlc()
print(f'Máximo de Concentração de Álcool que uma pessoa pode alcançar em seu corpo: {c} g/L', end='')

tmax = timeMaxConc()
print(f'\n\nTempo que a pessoa irá atingir esse nível máximo de concentração de álcool no corpo: {tmax} horas.', end='')

sobrio = tempoSobrio()
print(f'\n\nO indivíduo ficará sóbrio após {sobrio} horas do início da cachaçada.', end='')

"""8) Para ler um arquivo de .txt simples no Python, podemos utilizar a função open(),
que tem como parâmetro obrigatório o nome ou caminho onde está o arquivo.
Outro parâmetro importante, mas que já tem um valor padrão definido é o mode.
Este parâmetro indica em que modo o arquivo será aberto, como é possível ver
na tabela a seguir:

Caso nenhum valor seja definido para mode, o padrão é mode=’r’. Existem
outros parâmetros padrão que você pode conhecer nesse link
https://docs.python.org/3/library/functions.html#open.

Quando a função open é utilizada em modo leitura, ela retorna uma lista em que
cada elemento é uma linha escrita do arquivo. Com estas informações, crie duas
funções, uma para ler e exibir os dados de um arquivo e outra para escrever de
forma incremental os textos que o usuário for inserindo. Estas funções devem
ser chamados por um ou mais programas. O de escrita deve ser chamado
enquanto o usuário inserir textos não-vazios. Ao final, o programa deve exibir o
arquivo depois de escrito. Obs: Não esquecer de fechar o arquivo no fim da
leitura e da escrita.
"""

def Ler_Exibir_Dados(arquivo):
  with open(arquivo,'r') as file: # with fecha o arquivo
    texto = file.readlines()
    return texto

def Escrever(arquivo):
  while True:
    dado = str(input('Digite informações para serem escritas no arquivo: '))
    print('')
    if dado == '':
      print('DADOS INSERIDOS NO ARQUIVO!')
      break
    with open(arquivo,'a') as arq: # with fecha o arquivo
      arq.write(dado)

print('')
print('-' * 50)
print('{:^50}'.format('LENDO E ESCREVENDO EM UM ARQUIVO'))
print('-' * 50)
print('')

Escrever('planilhas.txt')

print('Este é o texto completo com os dados informados:\n ')
Ler_Exibir_Dados('planilhas.txt')

