# -*- coding: utf-8 -*-
"""Lista_Exercicios1_Aldenis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oBKR-muS_ZuZ63_J6J3y8yxI2G-LiI79

###IFPE Jaboatão
###Tecnologia em Análise e Desenvolvimento de Sistemas
###Disciplina: Lógica de Programação
###Professora: Havana Alves
###Aluno: Aldenis Everton Alves Guilherme de França

##Lista de Exercícios 1

1) Corrija as afirmações que estiverem incorretas:

a) 0.02 é um valor numérico inteiro
###Errado. 0.02 é um valor numérico real

b) -65.89 não é um valor numérico real
###Errado. -65.89 é um valor numérico real

c) “Maria” é um valor do tipo conjunto de caracteres.
###Correto.

d) 15 é um valor lógico inteiro
###Errado. 15 é um valor numérico inteiro

e) true é um valor conjunto de caracteres
###Errado. True é um tipo de dado booleano

f) ‘2558’ é um valor numérico inteiro
###Errado. ‘2558’ é um dado tipo string

g) “true” não é um valor lógico
###Correto.

h) “35.6003” não é um valor numérico real
###Correto.

i) false é um valor lógico
###Errado. false não é um valor lógico, mas False o é

###Programando com Python

2) Escreva um programa que pede ao usuário para entrar a largura e o comprimento de uma sala em formato retangular. Uma vez que os valores forem lidos, seu programa deve calcular e exibir a área dessa sala. Os valores lidos deverão ser do tipo float.
"""

print('CÁLCULO DA ÁREA DA SALA')

largura = input('Digite o valor da largura (em m): ')
largura = float(largura.replace("," , "."))

comprimento = input('Digite o valor do comprimento (em m): ')
comprimento = float(comprimento.replace("," , "."))

print('\nA área da sala é de {:.2f} m²'.format(largura*comprimento))

"""3) Faça um algoritmo que pegue a base e a altura em metros de um lote de terra de formato triangular. Calcule a área em metros quadrados e forneça esta área em hectares."""

print('CÁLCULO DA ÁREA DE UM TERRENO TRIANGULAR')

base = input('Digite o valor da base (em m): ')
base = base.replace("," , ".")
base = float(base)

altura = input('Digite o valor da altura (em m): ')
altura = altura.replace("," , ".")
altura = float(altura)

print('\nA área do terreno é de {:.4f} hectares.'.format((base*altura/2)/10000))

"""4) Uma iniciativa ecológica paga pequenos valores em dinheiro para incentivar as pessoas a reciclar recipientes de bebidas. Para cada recipiente de 1 litro são pagos 10 centavos e 2 litros, 25 centavos. Escreva um programa que leia a quantidade de recipientes de 1 litro e quantidade de recipientes de 2 litros e calcule e imprima no final o valor recebido pelo usuário. Imprima este valor acrescentando o R$."""

print('CÁLCULO DO VALOR RECEBIDO PELO USUÁRIO EM UMA INICIATIVA ECOLÓGICA')

recip1lt = int(input('Digite a quantidade de recipientes de 1 litro: '))
recip2lt = int(input('Digite a quantidade de recipientes de 2 litros: '))

print('\nO valor recebido pelo usuário é de R$ {}'.format((recip1lt*0.1)+(recip2lt*0.25)))

"""5) Escreva uma algoritmo que peça ao usuário valor de uma refeição pedida em um
restaurante. O programa deve então calcular a gorjeta resultante da refeição. Use o valor de 10% para calcular a gorjeta dada ao garçom. A saída do seu programa deve conter o valor da refeição, o valor da gorjeta e o valor final juntando estes dois valores. Utilize o R$ nos valores.
"""

print('CÁLCULO DA CONTA EM UM RESTAURANTE')

precoKg = 31.99
pesoPrato = input('Qual o peso do prato do cliente (em gramas): ')
pesoPrato = pesoPrato.replace("," , ".")
pesoPrato = float(pesoPrato)

valorPrato = pesoPrato*(precoKg/1000)
gorjeta = valorPrato*0.1
valorTotal = valorPrato + gorjeta

print('\nO valor do prato é de R$ {:.2f} \nO valor da gorjeta do garçom é de R$ {:.2f}\nValor total = R$ {:.2f}'.format(valorPrato,gorjeta,valorTotal))

"""6) Escreva um programa que leia um inteiro positivo n do usuário e então exiba a soma de todos os inteiros de 1 a n , que é calculada pela fórmula a seguir:
soma = n*(n+1) / 2
"""

print('SOMA DOS NÚMEROS INTEIROS DE 1 A n')

numInt = int(input('Digite um número inteiro a partir de 1: '))
somaInt = int((numInt * (numInt + 1)) / 2)

print('\nA soma dos números inteiros de 1 a {} é: {}'.format(numInt,somaInt))

"""7) Escreva um programa que peça um raio r . A partir desse raio, o programa deve calcular e exibir a área de um círculo de raio r e o volume de uma esfera também de raio r . Lembre que a área de um círculo é calculado por π * r² e o volume por 4 * π * r³. Considere π = 3.1415"""

print('CÁLCULO DA ÁREA DE UM CÍRCULO E DO VOLUME DE UMA ESFERA')

raio = input('Digite o raio do elemento circular (em cm): ')
raio = raio.replace("," , ".")
raio = float(raio)
pi = 3.1415

areaCir = pi * (raio ** 2)
volEsf = 4 * pi * (raio ** 3)

print('\nA área do círculo é de {:.2f} cm² e o volume da esfera é de {:.2f} cm³'.format(areaCir,volEsf))

"""8) Escreva um algoritmo que receba o preço unitário e a quantidade de mercadoria
adquirida. Calcule o total da compra.
"""

print('CÁLCULO DAS COMPRAS EM UM MERCADINHO')

feijao = input('Digite o preço de 1 kg de FEIJÃO: R$ ')
feijao = feijao.replace("," , ".")
feijao = float(feijao)
qtdFeijao = input('Digite a quantidade de kg de feijão comprada: ')
qtdFeijao = qtdFeijao.replace("," , ".")
qtdFeijao = float(qtdFeijao)
valorFeijao = feijao * qtdFeijao

arroz = input('Digite o preço de 1 kg de ARROZ: R$ ')
arroz = arroz.replace("," , ".")
arroz = float(arroz)
qtdArroz = input('Digite a quantidade de kg de arroz comprada: ')
qtdArroz = qtdArroz.replace("," , ".")
qtdArroz = float(qtdArroz)
valorArroz = arroz * qtdArroz

macarrao = input('Digite o preço de 1 kg de MACARRÃO: R$ ')
macarrao = macarrao.replace("," , ".")
macarrao = float(macarrao)
qtdMacarrao = input('Digite a quantidade de kg de macarrão comprada: ')
qtdMacarrao = qtdMacarrao.replace("," , ".")
qtdMacarrao = float(qtdMacarrao)
valorMacarrao = macarrao * qtdMacarrao

print('\nO valor total da compra foi de R$ {:.2f}'.format(valorFeijao+valorArroz+valorMacarrao))

"""9) Calcule o tempo de uma viagem de carro. Pergunte a distância a percorrer e a
velocidade média esperada para a viagem.
"""

print('CÁLCULO DAS COMPRAS EM UM MERCADINHO')

dist = input('Digite a distância a ser percorrida pelo carro (em km): ')
dist = dist.replace("," , ".")
dist = float(dist)

velMedia = input('Digite a velocidade média do carro esperada na viagem (em km/h): ')
velMedia = velMedia.replace("," , ".")
velMedia = float(velMedia)

tempoViagem = dist / velMedia

print('\nO tempo esperado da viagem é {:.2f} horas.'.format(tempoViagem))

"""10) Escrever um algoritmo que realize a conversão de uma temperatura fornecida
em graus Fahrenheit para graus centígrados (Celsius). O diálogo em algum
momento deve pedir a temperatura em Fahrenheits e expressá-la em Celsius.
"""

print('CONVERSÃO DE TEMPERATURA')

fahrenheit = input('Digite a temperatura em graus Fahrenheit (°F): ')
fahrenheit = fahrenheit.replace("," , ".")
fahrenheit = float(fahrenheit)

conversao = (fahrenheit - 32) * (5 / 9)

print('\nO valor da temperatura em graus Celsius é {:.2f} °C.'.format(conversao))