# -*- coding: utf-8 -*-
"""Lista_Exercicios2_Aldenis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jHwAfjJwf9ApztdexbPmqw1BhOySqhGZ

###IFPE Jaboatão
###Tecnologia em Análise e Desenvolvimento de Sistemas
###Disciplina: Lógica de Programação
###Professora: Havana Alves
###Aluno: Aldenis Everton Alves Guilherme de França

##Lista de Exercícios 2

1) Escreva um programa que leia um inteiro do usuário. Depois, seu programa deve exibir uma mensagem indicando se o inteiro é par ou ímpar.
"""

num = int(input('Digite um número inteiro: '))
if num % 2 == 0:
  print('\nO número {} é par!'.format(num))
else:
  print('\nO número {} é ímpar!'.format(num))

"""2) É comumente dito que 1 ano humano é equivalente a 7 anos caninos. Porém,
esta simples conversão falha em reconhecer que cães alcançam a vida adulta com
aproximadamente dois anos de idade. Como resultado disso, acredita-se que é
melhor contar contar cada um dos dois primeiros anos humanos como 10.5 anos
caninos, e após isso, contar cada ano humano adicional como 4 anos caninos.


Escreva um programa que receba o valor de anos humanos e implemente a
conversão para anos caninos de acordo com a descrição dada anteriormente.
Certifique-se de que seu programa trabalhe corretamente para conversões de
menos de dois anos humanos, bem como para conversões de dois ou mais anos
humanos. Seu programa deve descrever um erro apropriado, caso o usuário entre
com um número negativo.
"""

idadeHum = input('Digite a sua idade humana: ')
idadeHum = float(idadeHum.replace("," , "."))
if idadeHum >= 2:
  idadeCan = 21 + (4 * (idadeHum - 2))
  print('\nA idade do seu cachorro é {} anos.'.format(idadeCan))
elif idadeHum < 2 and idadeHum > 0:
  idadeCan = idadeHum * 10.5
  print('\nA idade do seu cachorro é {} anos.'.format(idadeCan))
else:
  print('\nErro! Você digitou um número inválido. Tente novamente!')

"""3) A quantidade de dias dos meses variam de 28 a 31. Você deve criar um
programa que receba o nome de um mês. Logo depois, deve-se exibir a quantidade
de dias do mês inserido. Obs: exiba “28 ou 29 dias” para Fevereiro.
"""

mes = input('Digite o nome do mês: ').lower()
if mes == 'fevereiro':
  print('\nO mês de {} tem 28 ou 29 dias.'.format(mes))
elif mes == 'abril' or mes == 'junho' or mes == 'setembro' or mes == 'novembro':
  print('\nO mês de {} tem 30 dias.'.format(mes))
elif mes == 'janeiro' or mes == 'março' or mes == 'maio' or mes == 'julho' or mes == 'agosto' or mes == 'outubro' or mes == 'dezembro':
  print('\nO mês de {} tem 31 dias.'.format(mes))
else:
  print('\nMês digitado inválido! Tente novamente!')

"""4) Os computadores apenas armazenam informação em valores que estão
codificados em código binário, em formato de zeros e uns. Para se codificar um
texto, é necessário que se adote um valor binário para cada caractere, letra ou
número do alfabeto. O código mais simples utilizado em sistemas computacionais é
o código ASCII (Sigla de American Standard Code for Information Exchange), que
está representada na imagem a seguir. Perceba que cad caracter tem sua
representação em Decimal (no caso é um valor inteiro), Hexadecimal e a sua
visualização como caracter. Sabendo que existe no Python a função ord() que
converte um carácter em sua representação decimal, crie um programa que receba
uma letra do alfabeto, e indique se esta letra é maiúscula ou minúscula. Você deve utilizar as informações da tabela ASCII para resolver esta questão. A seguir está uma forma de uso da função ord().
num = ord(“a”)
print(num)
"""

letra = input('Digite uma letra do alfabeto: ')
num = ord(letra)
if num >= 65 and num < 91:
  print('\nA letra {} é maiúscula!'.format(letra))
elif num >= 97 and num < 123:
  print('\nA letra {} é minúscula!'.format(letra))
else:
  print('\nVocê digitou um valor inválido! Tente novamente!')

"""5) Escreva um programa que determine o nome de uma forma geométrica a partir
do número de lados. Seu programa deve dar suporte a qualquer forma que
contenha no mínimo 3 e no máximo 10 lados. Se o número de lados estiver abaixo
ou acima deste limite, deve ser exibida uma mensagem de erro apropriada.
"""

qtdLados = int(input('Digite o número de lados da forma geométrica (de 3 a 10 lados): '))

if qtdLados == 3:
  print('\nA forma geométrica de {} lados é um Triângulo.'.format(qtdLados))
elif qtdLados == 4:
  print('\nA forma geométrica de {} lados é um Quadrilátero.'.format(qtdLados))
elif qtdLados == 5:
  print('\nA forma geométrica de {} lados é um Pentágono.'.format(qtdLados))
elif qtdLados == 6:
  print('\nA forma geométrica de {} lados é um Hexágono.'.format(qtdLados))
elif qtdLados == 7:
  print('\nA forma geométrica de {} lados é um Heptágono.'.format(qtdLados))
elif qtdLados == 8:
  print('\nA forma geométrica de {} lados é um Octágono.'.format(qtdLados))
elif qtdLados == 9:
  print('\nA forma geométrica de {} lados é um Eneágono.'.format(qtdLados))
elif qtdLados == 10:
  print('\nA forma geométrica de {} lados é um Decágono.'.format(qtdLados))
else:
  print('\nVocê digitou um valor inválido! Tente novamente!')

"""6) Escreva um programa que leia um nível de som em decibéis e se este for
exatamente igual a algum dos níveis mostrados na tabela exiba o nome do que
causa este barulho. Caso o valor esteja entre dois destes níveis, exiba entre 
quais destes barulhos o nível se encontra. Ex: 115 dB está entre o barulho de um
cortador de grama a gás e uma britadeira.

Caso, o nível esteja abaixo do menor valor da tabela e acima do maior valor, exiba mensagens adequadas indicando estes fatos.
"""

nivelSom = input('Digite o valor do Nível Sonoro, em dB: ')
nivelSom = float(nivelSom.replace(',','.'))

britadeira = 130
cortador = 106
despertador = 70
sala = 40

if nivelSom == britadeira:
   print('\nO Nível Sonoro de {} dB corresponde ao de uma Britadeira.'.format(nivelSom))
elif nivelSom < britadeira and nivelSom > cortador:
  print('\nO Nível Sonoro de {} dB está entre barulho de um cortador de grama a gás e uma britadeira.'.format(nivelSom))

elif nivelSom == cortador:
   print('\nO Nível Sonoro de {} dB corresponde ao de um Cortador de grama a gás.'.format(nivelSom))
elif nivelSom < cortador and nivelSom > despertador:
  print('\nO Nível Sonoro de {} dB está entre barulho de um despertador e um cortador de grama a gás.'.format(nivelSom))

elif nivelSom == despertador:
   print('\nO Nível Sonoro de {} dB corresponde ao de um Despertador.'.format(nivelSom))
elif nivelSom < despertador and nivelSom > sala:
  print('\nO Nível Sonoro de {} dB está entre barulho de uma sala tranquila e um despertador.'.format(nivelSom))

elif nivelSom == sala:
   print('\nO Nível Sonoro de {} dB corresponde ao de uma Sala tranquila.'.format(nivelSom))
elif nivelSom < sala:
  print('\nO Nível Sonoro de {} dB é menor do que o de uma Sala tranquila.'.format(nivelSom))

else:
  print('\nO Nível Sonoro de {} dB é maior do que o de uma Britadeira.'.format(nivelSom))

"""7) O ano é dividido em quatro estações: primavera, verão, outono e inverno. De
forma geral o calendário das estações está na tabela a seguir:

Crie um programa que leia o mês (nome do mês) e o dia. O programa deve exibir
qual a estação associada à data inserida.
"""

mes = input('Digite o nome do mês: ').lower()
dia = int(input('Digite o dia desse mês: '))

if mes == 'janeiro' or mes == 'fevereiro':
  print('Na data de {} de {} é VERÃO!'.format(dia, mes))
elif mes == 'abril' or mes == 'maio':
  print('Na data de {} de {} é OUTONO!'.format(dia, mes))
elif mes == 'julho' or mes == 'agosto':
  print('Na data de {} de {} é INVERNO!'.format(dia, mes))
elif mes == 'outubro' or mes == 'novembro':
  print('Na data de {} de {} é PRIMAVERA!'.format(dia, mes))

elif mes == 'março' and dia < 20:
  print('Na data de {} de {} é VERÃO!'.format(dia, mes))
elif mes == 'março' and 31 > dia >= 20:
  print('Na data de {} de {} é OUTONO!'.format(dia, mes))

elif mes == 'junho' and dia < 21:
  print('Na data de {} de {} é OUTONO!'.format(dia, mes))
elif mes == 'junho' and 30 > dia >= 21:
  print('Na data de {} de {} é INVERNO!'.format(dia, mes))

elif mes == 'setembro' and dia < 22:
  print('Na data de {} de {} é INVERNO!'.format(dia, mes))
elif mes == 'setembro' and 30 > dia >= 22:
  print('Na data de {} de {} é PRIMAVERA!'.format(dia, mes))  

elif mes == 'dezembro' and dia < 21:
  print('Na data de {} de {} é PRIMAVERA!'.format(dia, mes))
elif mes == 'dezembro' and 31 > dia >= 21:
  print('Na data de {} de {} é VERÃO!'.format(dia, mes))

else:
  print('Dia ou mês inválido! Tente novamente!')

"""8) No Brasil, as cédulas são representadas por animais que estão em extinção na
fauna do país. Assim, a tabela a seguir exibe os valores das cédulas e os animais correspondentes:

Escreva um programa que receba um valor em reais (sem centavos) e indique
quantos animais de cada espécie o usuário irá carregar no bolso, de forma que se
tenha o mínimo de cédulas possível. Ex: R$ 32,00 → 1 nota de R$ 20, 1 nota de R$
10 e uma nota de R$ 2, que resulta em Um mico-leão, uma arara e uma tartaruga
de pente.
"""

dinheiro = int(input('Informe quantas cédulas de reais você tem no bolso: R$ '))

if dinheiro % 200 == 0:
  cedulas = (dinheiro / 200)
else:
  if dinheiro % 10 == 1:
    cedMen = ' 1 Garça e 3 Tartaruga(s) de pente '
  elif dinheiro % 10 == 3:
    cedMen = ' 1 Garça e 4 Tartaruga(s) de pente '
  elif dinheiro % 10 == 6:
    cedMen = ' 3 Tartaruga(s) de pente '
  elif dinheiro % 10 == 7:
    cedMen = ' 1 Garça e 1 Tartaruga(s) de pente '
  elif dinheiro % 10 == 8:
    cedMen = ' 4 Tartaruga(s) de pente '
  elif dinheiro % 10 == 9:
    cedMen = ' 1 Garça e 2 Tartaruga(s) de pente '
  else:
    cedMen = ''
  print('\nVocê tem {} Lobo(s)-guará'.format(cedulas) + cedMen + 'no bolso'.format(cedulas) )

if dinheiro % 100 == 0:
  cedulas = (dinheiro / 100)
  print('\nVocê tem {} Garoupa(s) no bolso.'.format(cedulas))
elif dinheiro % 50 == 0:
  cedulas = (dinheiro / 50)
  print('\nVocê tem {} Onça(s)pintada(s) no bolso.'.format(cedulas))
elif dinheiro % 20 == 0:
  cedulas = (dinheiro / 20)
  print('\nVocê tem {} Mico(s)-leão(ões)-dourado(s) no bolso.'.format(cedulas))
elif dinheiro % 10 == 0:
  cedulas = (dinheiro / 10)
  print('\nVocê tem {} Arara(s) no bolso.'.format(cedulas))
elif dinheiro % 5 == 0:
  cedulas = (dinheiro / 5)
  print('\nVocê tem {} Garça(s) no bolso.'.format(cedulas))
elif dinheiro % 2 == 0:
  cedulas = (dinheiro / 2)
  print('\nVocê tem {} Tartaruga(s) de pente no bolso.'.format(cedulas))
else:
   print('\nVocê digitou um valor com centavos ou menor que R$ 2,00. Tente novamente!' )

"""9) Implemente um programa que lê como entrada o preço de custo de um produto e
o código relativo à categoria do produto. De acordo com a tabela dada a seguir,
deve ser calculado o preço de venda do produto, levando em conta a margem de
lucro calculada sobre o preço de custo do produto:
"""

codProd = int(input('Informe o código do produto (de 1 a 6): '))
custo = input('Informe o custo desse produto, em R$: ')
custo = float(custo.replace(',','.'))

if codProd == 1:
  produto = 'Hortifruti'
  print('\nO preço de venda de {} é R$ {:.2f}'.format(produto,1.8*custo))
elif codProd == 2:
  produto = 'Laticíneos'
  print('\nO preço de venda de {} é R$ {:.2f}'.format(produto,1.8*custo))
elif codProd == 3:
  produto = 'Carnes'
  print('\nO preço de venda de {} é R$ {:.2f}'.format(produto,2*custo))
elif codProd == 4:
  produto = 'Peixes'
  print('\nO preço de venda de {} é R$ {:.2f'.format(produto,2*custo))
elif codProd == 5:
  produto = 'Aves'
  print('\nO preço de venda de {} é R$ {:.2f}'.format(produto,1.9*custo))
elif codProd == 6:
  produto = 'Ovos'
  print('\nO preço de venda de {} é R$ {:.2f}'.format(produto,1.9*custo))
else:
  print('\nCódigo inválido. Tente novamente!')

"""10) Um posto de gasolina tem a seguinte tabela de preços:

Crie um programa que receba o código do combustível comprado e a quantidade, e
imprima o valor que o cliente deverá pagar.
"""

codComb = int(input('Informe o código do combustível (1 - Álcool ou 2 - Gasolina): '))
litros = input('Informe quantos litros você deseja comprar: ')
litros = float(litros.replace(',','.'))

if codComb == 1 and litros <= 20:
  preco = 3.16
  custo = preco * litros
  print('\nVocê deve pagar R$ {:.2f} por {} litros de Álcool.'.format(custo,litros))

elif codComb == 1 and litros > 20:
  preco = 3.14
  custo = preco * litros
  print('\nVocê deve pagar R$ {:.2f} por {} litros de Álcool.'.format(custo,litros))

elif codComb == 2 and litros <= 30:
  preco = 4.20
  custo = preco * litros
  print('\nVocê deve pagar R$ {:.2f} por {} litros de Gasolina.'.format(custo,litros))

elif codComb == 2 and litros > 30:
  preco = 4.19
  custo = preco * litros
  print('\nVocê deve pagar R$ {:.2f} por {} litros de Gasolina.'.format(custo,litros))

else:
  print('\nVocê digitou um código inexistente! Tente novamente!')