# -*- coding: utf-8 -*-
"""Lista_Exercicios4_Aldenis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bhtn9yNBrebHFsx_vWwEbqLDG4IY9zyO

###IFPE Jaboatão
###Tecnologia em Análise e Desenvolvimento de Sistemas
###Disciplina: Lógica de Programação
###Professora: Havana Alves
###Aluno: Aldenis Everton Alves Guilherme de França

##Lista de Exercícios 4

1. Faça um programa que receba a idade de quinze pessoas e que calcule e mostre a quantidade de pessoas com idade maior ou igual a 18 anos.
"""

maior = 0
for i in range(1,16):
  idade = int(input('Digite sua idade: '))
  if idade >= 18:
    maior = maior + 1
print(f'\nHá {maior} pessoa(s) com idade maior ou igual a 18 anos.')

"""2. Uma loja tem 15 Clientes cadastrados e deseja enviar uma correspondência
a cada um deles, anunciando um bônus especial. Faça um programa que
leia o nome do cliente e o valor de suas compras no ano passado. Calcule e
mostre um bônus de 10% se o valor das compras for menor que R$ 1000,00
e de 15%, caso contrário.
"""

for i in range(1,16):
  nome = input('Digite o nome do cliente: ')
  compras = input('Digite o valor das suas compras no ano passado: ')
  compras = float(compras.replace(',','.'))
  if compras < 1000:
    print('\nParabéns, {}! Você ganhou um bônus de 10% em relação às suas compras do ano passado, totalizando R$ {:.2f}\n'.format(nome,0.1*compras))
  else:
    print('\nParabéns, {}! Você ganhou um bônus de 15% em relação às suas compras do ano passado, totalizando R$ {:.2f}\n'.format(nome,0.15*compras))

"""3. Foi realizada uma pesquisa de algumas características físicas da população
de uma certa região, a qual coletaram os seguintes dados referentes a cada
habitante para serem analisados. Receba do usuário a quantidade de
habitantes dessa região e para cada habitante solicite:
- cor dos olhos (azuis, verdes ou castanhos)
- cor dos cabelos (louros, castanhos, pretos)
- idade

Faça um algoritmo que determine e escreva:

a) a maior idade dos habitantes;

b) a quantidade de indivíduos de olhos castanhos cuja idade está entre
18 e 35 anos, inclusive;

c) a quantidade de indivíduos que tenham olhos verdes e cabelos
louros;
"""

hab = int(input('Informe a quantidade de pessoas dessa região: '))
aux_idade = jovensCastanhos = lourosVerdes = 0

for i in range(1,hab+1):
  olho = int(input('\nQual a cor dos olhos do habitante nº{}? Digite:\n1 - Azul\n2 - Verde\n3 - Castanho: '.format(i)))
  cabelo = int(input('\nQual a cor dos cabelos do habitante nº{}? Digite:\n1 - Louros\n2 - Castanhos\n3 - Pretos: '.format(i)))
  idade = int(input('\nQual a idade do habitante nº{}? '.format(i)))

  if idade >= aux_idade:
    aux_idade = idade

  if 18 <= idade <= 35 and olho == 3:
    jovensCastanhos = jovensCastanhos + 1

  if olho == 2 and cabelo == 1:
    lourosVerdes = lourosVerdes + 1

maiorIdade = aux_idade

print('')
print('-' * 80)
print('{:^80}'.format('RESULTADOS'))
print('-' * 80)
print(f'\nA pessoa de maior idade tem {maiorIdade} anos.\nHá {jovensCastanhos} pessoa(s) de olhos castanhos e idade entre 18 e 35 anos.'
f'\nHá {lourosVerdes} pessoa(s) de olhos verdes e cabelos louros.')

"""4. Chico tem 1,50 metros e cresce 2 centímetros por ano, enquanto Zé tem 1,10
metros e cresce 3 centímetros por ano. Construa um algoritmo que calcule e
imprima quantos anos serão necessários para que Zé seja maior que Chico.
"""

altChico = 150
altZe = 110
tempo = 0

for i in range(altZe,altChico+1):
  altChico = altChico + 2
  altZe = altZe + 3
  tempo = tempo + 1

print(f'Serão necessários {tempo} anos para Zé ser mais alto que Chico. Zé estará com {altZe/100} m de altura e Chico com {altChico/100} m.')

"""5. Foi feita uma pesquisa com um grupo de 5 alunos de uma universidade, na
qual se perguntou para cada aluno o número de vezes que utilizou o
restaurante da universidade no último mês. Construa um algoritmo que
determine:

a) O percentual de alunos que utilizaram menos que 10 vezes o
restaurante;

b) O percentual de alunos que utilizaram entre 10 e 15 vezes;

c) O percentual de alunos que utilizaram o restaurante acima de 15
vezes.
"""

alunos = 5
menos = media = mais = 0

for i in range(1,alunos+1):
  qtdRest = int(input('Quantas vezes você utilizou o restaurante no último mês? '))

  if 0 < qtdRest < 10:
    menos = menos + 1
  elif 10 <= qtdRest <= 15:
    media = media + 1
  else:
    mais = mais + 1

print('')
print('-' * 80)
print('{:^80}'.format('RESULTADOS'))
print('-' * 80)
print('\nPorcentagem de alunos que utilizaram o restaurante menos que 10 vezes: {:.2f}%'.format((menos/alunos)*100))
print('Porcentagem de alunos que utilizaram o restaurante entre 10 e 15 vezes: {:.2f}%'.format((media/alunos)*100))
print('Porcentagem de alunos que utilizaram o restaurante acima de 15 vezes: {:.2f}%'.format((mais/alunos)*100))

"""6. Um pesquisador entrevistou 20 pessoas em um cinema. Cada entrevistado
respondeu a um questionário no qual constava sua opinião em relação ao filme: Ótimo - 3, Bom - 2, Regular - 1 e sua idade . Faça um programa que
receba a opinião de vários espectadores e que calcule e mostre :

● a quantidade de pessoas que respondeu Ótimo;

● a quantidade de pessoas que respondeu Bom;

● a quantidade de pessoas que respondeu Regular;
"""

regular = bom = otimo = 0

for i in range(1,21):
  opiniao = int(input('\nQual sua opinião sobre o filme, {}º entrevistado? Digite:\n1 - Regular\n2 - Bom\n3 - Ótimo: '.format(i)))
  idade = int(input('\nQual sua idade, {}º entrevistado? '.format(i)))

  if opiniao == 1:
    regular = regular + 1
  elif opiniao == 2:
    bom = bom + 1
  elif opiniao == 3:
    otimo = otimo + 1

print('')
print('-' * 80)
print('{:^80}'.format('RESULTADOS'))
print('-' * 80)
print('\n{} pessoa(s) classificaram o filme como REGULAR.\n{} pessoa(s) classificaram o filme como BOM.'
'\n{} pessoa(s) classificaram o filme como ÓTIMO.'.format(regular,bom,otimo))

"""7. Faça um programa que receba a idade de várias pessoas. A quantidade de pessoas que serão entrevistadas deverá ser fornecido pelo usuário que está fazendo a pesquisa. Ao final, calcule e mostre:
-a quantidade de pessoas em cada faixa etária descrita a seguir:

Faixa Etária Idade

1ª De 0 a 5 anos

2ª De 6 a 13 anos

3ª De 14 a 17 anos

4ª De 18 a 59 anos

5ª Acima de 60 anos
"""

pri = seg = ter = qua = qui = 0

qtdPes = int(input('Digite a quantidade de pessoas que serão entrevistadas: '))

for i in range(1,qtdPes+1):
  idade = int(input('\nDigite sua idade, {}º entrevistado? '.format(i)))
  if 0 <= idade <= 5:
    pri = pri + 1
  elif 6 <= idade <= 13:
    seg = seg + 1
  elif 14 <= idade <= 17:
    ter = ter + 1
  elif 18 <= idade <= 59:
    qua = qua + 1
  elif idade >= 60:
    qui = qui + 1

print('')
print('-' * 30)
print('Faixa Etária | Qtd. Pessoas')
print('-' * 30)
print('De 0 a 5 anos: {} pessoa(s)\nDe 6 a 13 anos: {} pessoa(s)\nDe 14 a 17 anos: {} pessoa(s)\nDe 18 a 59 anos: {} pessoa(s)'
'\nAcima de 60 anos: {} pessoa(s)'.format(pri,seg,ter,qua,qui))

"""8. Cada espectador de um cinema respondeu a um questionário no qual constava sua
opinião em relação ao filme: ótimo - 3, bom - 2, regular - 1 e sua idade . Faça um programa que receba a opinião de vários espectadores e que calcule e mostre:

● a média das idades das pessoas que responderam ótimo;

● a quantidade de pessoas que respondeu regular.

● a percentagem de pessoas que respondeu bom entre todos os espectadores
analisados.

O programa deve parar quando for digitada uma opinião igual a 4.
"""

regular = bom = otimo = cont = aux_idade = 0

for i in range(1,10**100):
  opiniao = ' '
  while opiniao not in '1234':
    opiniao = input('\nQual sua opinião sobre o filme, {}º entrevistado? Digite:\n1 - Regular\n2 - Bom\n3 - Ótimo\n4 - PARA SAIR: '.format(i)).strip()[0]
  if opiniao == '4':
    break
  idade = int(input('\nQual sua idade, {}º entrevistado? '.format(i)))
  cont = cont + 1
  if opiniao == '1':
    regular = regular + 1
  elif opiniao == '2':
    bom = bom + 1
  elif opiniao == '3':
    otimo = otimo + 1
    aux_idade = aux_idade + idade

if otimo == 0:
  otimo = 1

print('')
print('-' * 80)
print('{:^80}'.format('RESULTADOS'))
print('-' * 80)
print('{} pessoa(s) classificaram o filme como REGULAR.\n{:.2f}% é a porcentagem de pessoa(s) que classificaram o filme como BOM.'
'\n{:.2f} é a média das idades das pessoa(s) que classificaram o filme como ÓTIMO.'.format(regular,100*(bom/cont),aux_idade/otimo))

"""9. Escreva um algoritmo que leia um número n (número de termos de uma progressão
aritmética), a1 (o primeiro termo da progressão) e 

r (a razão da progressão) e
escreva os n termos desta progressão, bem como a soma dos elementos.
"""

n = int(input('Digite o número de termos da Progressão Aritmética: '))
a1 = int(input('Digite o primeiro termo da Progressão Aritmética: '))
r = int(input('Digite o razão da Progressão Aritmética: '))
soma = a1

print('\nOs {} termos dessa Progressão Aritmética (P.A.) são: '.format(n))
print(a1)

for i in range(1,n):
  a1 = a1 + r
  print(a1)
  soma = soma + a1
print('\nA soma dos termos dessa Progressão Aritmética (P.A.) é: {}'.format(soma))

"""10. Crie um algoritmo que simule o funcionamento de um caixa de supermercado. O
caixa fica aberto até o fim do expediente e pode processar a compra de até 10
clientes. Cada cliente pode comprar vários itens. Ao ler cada item deve ser exibida uma mensagem para o operador do caixa. Resolva com um laço for e um laço while na mesma solução.
"""

for i in range(1,11):
  print('-' * 20)
  print('     CLIENTE {}'.format(i))
  print('-' * 20)
  print('')
  preco = 1
  subtotal = 0
  while preco != 0:
    preco = input('Preço do produto (ou 0 para sair): ')
    preco = float(preco.replace(',','.'))
    if preco == 0:
      continue
    produto = input('Nome do produto: ').upper()
    qtd = int(input('Quantidade desse produto: '))
    aux_subtotal = preco*qtd

    print('')
    print('Produto: {}'.format(produto))
    print('Preço: R$ {:.2f}'.format(preco))
    print('Quantidade: {}'.format(qtd))
    subtotal = aux_subtotal + subtotal
    print('Subtotal: R$ {:.2f}'.format(subtotal))
    print('')
  print('')
  print('TOTAL A PAGAR PELO CLIENTE {}: R$ {:.2f}'.format(i,subtotal))
  print('')

