# -*- coding: utf-8 -*-
"""Lista_Exercicios9_Aldenis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PC4UyvEzr2pwVaQb8NduMw-AEnIGGqWL

###IFPE Jaboatão
###Tecnologia em Análise e Desenvolvimento de Sistemas
###Disciplina: Lógica de Programação
###Professora: Viviane Aureliano
###Aluno: Aldenis Everton Alves Guilherme de França

##Lista de Exercícios 9

1. Crie um programa que simule um editor de textos, da seguinte maneira: o usuário do editor pode digitar quantas sentenças quiser até que seja digitada uma sentença em branco.
2. Crie uma função que salve as sentenças digitadas pelo usuário em um arquivo chamado “texto.txt” quando o usuário pedir para salvar o arquivo.
3. Crie uma função que lê e exibe as sentenças salvas no arquivo.
4. Crie uma função que inclui novas sentenças no arquivo. O usuário pode incluir quantas sentenças quiser até que seja digitada uma sentença em branco.
5. Crie um menu por meio do qual o usuário pode utilizar cada uma das funções criadas.
"""

lista = []

def cabecalho(titulo):
  print('-' * 50)
  print('{:^50}'.format(titulo))
  print('-' * 50)

def escreverArquivo():
  cabecalho('ESCREVER PARA UM ARQUIVO')  
  while True:
    dado = input('Digite o Texto ou deixe em branco + ENTER para voltar ao Menu: ').strip()
    lista.append(dado)
    print('')
    if dado == '':
      print(colored('Você tem dados a serem salvos!','yellow'))
      break

def salvarArquivo():
  cabecalho('SALVAR ARQUIVO')
  arquivo = input('Informe o nome do arquivo a ser SALVO: ')
  arquivo += '.txt'
  with open(arquivo,'w') as file:    
    for i in lista:
      file.write(f'{i}\n')
    print(colored('\nArquivo Salvo com sucesso!','blue'))

def lerExibirDados():
  cabecalho('LER E EXIBIR ARQUIVO')
  arquivo = input('Informe um nome do arquivo a ser lido e exibido: ')
  arquivo += '.txt' 
  with open(arquivo,'r') as file:
    texto = file.read()
    print(texto[:-2])

def inserirNovoTexto():
  cabecalho('INSERIR NOVAS SENTENÇAS NO ARQUIVO')
  arquivo = input('Informe o nome do arquivo para escrever nele: ')
  arquivo += '.txt'
  print('')
  with open(arquivo,'a') as file:
    while True:
      dado = str(input('Digite o NOVO Texto ou deixe em branco + ENTER para voltar ao Menu: '))
      print('')
      if dado == '':
        print('NOVOS Dados Inseridos no Arquivo com Sucesso!')
        break
      file.write(f'{dado}\n')

def finalizarPrograma():
  opcao = False
  print('-' * 50)
  print(colored('Finalizando...','green',attrs=['bold']))
  print('-' * 50)
  sleep(2)

from termcolor import colored
from time import sleep

opcao = True
while opcao:
  cabecalho('MENU PRINCIPAL')

  print(colored('''  [ 1 ] Escrever para um Arquivo
  [ 2 ] Salvar o Arquivo
  [ 3 ] Ler e exibir o Arquivo
  [ 4 ] Incluir novas sentenças no Arquivo
  [ 5 ] Finalizar o Programa''','blue'))
  print('-' * 50)
  opcao = input('Sua Opção: ')

  if opcao == '1':
    escreverArquivo()
    sleep(1)
  elif opcao == '2':
    salvarArquivo()
    sleep(1)
  elif opcao == '3':
    lerExibirDados()
    sleep(1)
  elif opcao == '4':
    inserirNovoTexto()
    sleep(1)
  elif opcao == '5':
    finalizarPrograma()
    opcao = False
  else:
    print('-' * 50)
    print(colored('Opção Inválida! Tente novamente.','red',attrs=['bold']))
    sleep(1)
print(colored('Programa Finalizado com sucesso!','green',attrs=['bold']))